$:.unshift File.dirname(__FILE__)

def net
  Java::Net
end

require "endertromb/animal_array"
require "endertromb/crafting"
require "endertromb/item"
require "endertromb/block"
require "endertromb/item_stack"
require "endertromb/inventory"

require "endertromb/core_ext/string"
require "endertromb/core_ext/symbol"

require "endertromb/entity"
require "endertromb/entities/arrow"
require "endertromb/entities/bat"
require "endertromb/entities/blaze"
require "endertromb/entities/boat"
require "endertromb/entities/cave_spider"
require "endertromb/entities/chicken"
require "endertromb/entities/client_player_mp"
require "endertromb/entities/cow"
require "endertromb/entities/creeper"
require "endertromb/entities/dragon"
require "endertromb/entities/dragon_part"
require "endertromb/entities/egg"
require "endertromb/entities/ender_crystal"
require "endertromb/entities/ender_eye"
require "endertromb/entities/ender_pearl"
require "endertromb/entities/enderman"
require "endertromb/entities/exp_bottle"
require "endertromb/entities/firework_rocket"
require "endertromb/entities/fish_hook"
require "endertromb/entities/ghast"
require "endertromb/entities/giant_zombie"
require "endertromb/entities/golem"
require "endertromb/entities/iron_golem"
require "endertromb/entities/item_entity"
require "endertromb/entities/large_fireball"
require "endertromb/entities/lightning_bolt"
require "endertromb/entities/magma_cube"
require "endertromb/entities/minecart_chest"
require "endertromb/entities/minecart_container"
require "endertromb/entities/minecart_empty"
require "endertromb/entities/minecart_furnace"
require "endertromb/entities/minecart_hopper"
require "endertromb/entities/minecart_mob_spawner"
require "endertromb/entities/minecart_mob_spawner_logic"
require "endertromb/entities/minecart_tnt"
require "endertromb/entities/mooshroom"
require "endertromb/entities/ocelot"
require "endertromb/entities/other_player_mp"
require "endertromb/entities/painting"
require "endertromb/entities/pig"
require "endertromb/entities/pig_zombie"
require "endertromb/entities/player_mp"
require "endertromb/entities/player_sp"
require "endertromb/entities/potion"
require "endertromb/entities/sheep"
require "endertromb/entities/silverfish"
require "endertromb/entities/skeleton"
require "endertromb/entities/slime"
require "endertromb/entities/small_fireball"
require "endertromb/entities/snowball"
require "endertromb/entities/snowman"
require "endertromb/entities/spider"
require "endertromb/entities/squid"
require "endertromb/entities/tnt_primed"
require "endertromb/entities/villager"
require "endertromb/entities/witch"
require "endertromb/entities/wither"
require "endertromb/entities/wither_skull"
require "endertromb/entities/wolf"
require "endertromb/entities/xp_orb"
require "endertromb/entities/zombie"

module Endertromb
end

